# Generated by Django 5.2.8 on 2025-11-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(db_column='id_produto', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=200)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=500, null=True)),
                ('estoque_atual', models.IntegerField(db_column='estoque_atual')),
                ('estoque_min', models.IntegerField(db_column='estoque_min')),
            ],
            options={
                'db_table': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=150)),
                ('login', models.CharField(db_column='login', max_length=80, unique=True)),
                ('senha', models.CharField(db_column='senha', max_length=255)),
                ('ativo', models.BooleanField(db_column='ativo', default=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(db_column='id_movimentacao', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=10)),
                ('quantidade', models.IntegerField(db_column='quantidade')),
                ('data_movimentacao', models.DateField(db_column='data_movimentacao')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes', to='api.produto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='movimentacoes', to='api.usuario')),
            ],
            options={
                'db_table': 'movimentacoes',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
