# Generated by Django 5.2.8 on 2025-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(db_column='id_movimentacao', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=10)),
                ('quantidade', models.IntegerField(db_column='quantidade')),
                ('data_movimentacao', models.DateField(db_column='data_movimentacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
            ],
            options={
                'db_table': 'movimentacoes',
                'ordering': ['-criado_em'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(db_column='id_produto', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=200)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=500, null=True)),
                ('estoque_atual', models.IntegerField(db_column='estoque_atual', default=0)),
                ('estoque_min', models.IntegerField(db_column='estoque_min', default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='responsible',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
