# Generated by Django 5.2.8 on 2025-11-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movimentacao_produto_remove_stockmovement_product_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
