# Generated by Django 5.2.8 on 2025-11-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'managed': False, 'ordering': ['-data_movimentacao']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'managed': False, 'ordering': ['nome']},
        ),
    ]
