# Generated by Django 5.2.8 on 2025-11-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movimentacao_options_alter_produto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_movimentacao']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
